import type { Book } from '../types';

export const mockBooks: Book[] = [
  {
    id: '1',
    title: 'The Design of Everyday Things',
    author: 'Don Norman',
    coverUrl: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=400',
    category: 'Design',
    rating: 4.8,
    reviewsCount: 1200,
    publishedYear: 2013,
    pages: 368,
    language: 'English',
    synopsis: 'A classic book on the principles of design and usability.',
    location: 'Shelf A-1',
    publisher: 'Basic Books',
    available: true,
    libraryId: '1',
    createdAt: new Date().toISOString()
  },
  {
    id: '2',
    title: 'Dune',
    author: 'Frank Herbert',
    coverUrl: 'https://images.unsplash.com/photo-1541963463532-d68292c34b19?auto=format&fit=crop&q=80&w=400',
    category: 'Fiction',
    rating: 4.8,
    reviewsCount: 3500,
    publishedYear: 1965,
    pages: 412,
    language: 'English',
    synopsis: 'Set in the distant future amidst a huge interstellar empire.',
    location: 'Shelf F-4',
    publisher: 'Chilton Books',
    available: true,
    libraryId: '1',
    createdAt: new Date().toISOString()
  },
  {
    id: '3',
    title: 'Clean Architecture',
    author: 'Robert C. Martin',
    coverUrl: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&q=80&w=400',
    category: 'Computer Science',
    rating: 4.7,
    reviewsCount: 850,
    publishedYear: 2017,
    pages: 432,
    language: 'English',
    synopsis: 'A craftsman\'s guide to software structure and design.',
    location: 'Shelf CS-2',
    publisher: 'Prentice Hall',
    available: true,
    libraryId: '1',
    createdAt: new Date().toISOString()
  },
  {
    id: '4',
    title: 'Atomic Habits',
    author: 'James Clear',
    coverUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=400',
    category: 'Self-Help',
    rating: 4.9,
    reviewsCount: 50000,
    publishedYear: 2018,
    pages: 320,
    language: 'English',
    synopsis: 'An easy and proven way to build good habits and break bad ones.',
    location: 'Shelf SH-1',
    publisher: 'Penguin Publishing Group',
    available: true,
    libraryId: '1',
    createdAt: new Date().toISOString()
  },
  {
    id: '5',
    title: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    coverUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&q=80&w=400',
    category: 'History',
    rating: 4.6,
    reviewsCount: 25000,
    publishedYear: 2011,
    pages: 443,
    language: 'English',
    synopsis: 'Explores the history of the human species from a fresh perspective.',
    location: 'Shelf H-5',
    publisher: 'Harper',
    available: true,
    libraryId: '1',
    createdAt: new Date().toISOString()
  }
];
